# Generated by Django 5.1.15 on 2026-05-06 07:19

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('status', django_fsm.FSMField(choices=[('in_progress', 'בתהליך'), ('submitted', 'הוגש'), ('graded', 'נוקד')], default='in_progress', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score_pct', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('time_remaining_seconds_snapshot', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ניסיון מבחן',
                'verbose_name_plural': 'ניסיונות מבחן',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'course', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField()),
                ('question_version_at_attempt', models.PositiveIntegerField()),
                ('stem_html_snapshot', models.TextField()),
                ('options_snapshot_json', models.JSONField()),
                ('correct_option_index_snapshot', models.PositiveSmallIntegerField()),
                ('senior_insight_snapshot_he', models.TextField(blank=True)),
                ('explanation_snapshot_html_he', models.TextField(blank=True)),
                ('user_answer_option_index', models.SmallIntegerField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('confident', 'בטוח'), ('not_sure', 'לא בטוח')], max_length=10, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.examattempt')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_records', to='content.question')),
            ],
            options={
                'verbose_name': 'שאלת ניסיון',
                'verbose_name_plural': 'שאלות ניסיון',
                'ordering': ['display_order'],
                'unique_together': {('attempt', 'display_order')},
            },
        ),
    ]
