# Generated by Django 5.1.15 on 2026-05-06 07:19

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('file_key', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', django_fsm.FSMField(choices=[('submitted', 'הוגש'), ('under_review', 'בבדיקה'), ('passed', 'עבר'), ('failed', 'נכשל')], default='submitted', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capstone_submissions', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הגשת פרויקט גמר',
                'verbose_name_plural': 'הגשות פרויקט גמר',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneRubricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('analysis', 'ניתוח פיננסי'), ('risk', 'הערכת סיכונים'), ('structure', 'מבנה העסקה'), ('presentation', 'הצגה ותקשורת'), ('conclusion', 'מסקנות והמלצות')], max_length=20)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment_he', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_scores_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='capstone.capstonesubmission')),
            ],
            options={
                'verbose_name': 'ציון קריטריון',
                'verbose_name_plural': 'ציוני קריטריונים',
                'unique_together': {('submission', 'category')},
            },
        ),
    ]
