# Generated by Django 5.1.15 on 2026-05-06 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_he', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_he', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'תחום',
                'verbose_name_plural': 'תחומים',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_he', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'תג',
                'verbose_name_plural': 'תגים',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title_he', models.CharField(max_length=300)),
                ('description_he', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('phase', models.CharField(choices=[('A', "שלב א'"), ('B', "שלב ב'"), ('C', "שלב ג'"), ('D', "שלב ד'"), ('E', "שלב ה'")], max_length=1)),
                ('course_number', models.PositiveSmallIntegerField()),
                ('passing_score_pct', models.PositiveSmallIntegerField(default=75)),
                ('exam_question_count', models.PositiveSmallIntegerField(default=20)),
                ('exam_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_capstone', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='content.domain')),
            ],
            options={
                'verbose_name': 'קורס',
                'verbose_name_plural': 'קורסים',
                'ordering': ['course_number'],
                'unique_together': {('domain', 'course_number')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title_he', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('module_number', models.PositiveSmallIntegerField()),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'verbose_name': 'מודול',
                'verbose_name_plural': 'מודולים',
                'ordering': ['module_number'],
                'unique_together': {('course', 'module_number'), ('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_id_external', models.CharField(blank=True, max_length=50, unique=True)),
                ('question_type', models.IntegerField(choices=[(1, 'אחזור מידע'), (2, 'חישוב חד-שלבי'), (3, 'חישוב רב-שלבי'), (4, 'ניתוח מסמך'), (5, 'תרחיש'), (6, 'סינתזה')])),
                ('difficulty', models.CharField(choices=[('basic', 'בסיסי'), ('intermediate', 'בינוני'), ('advanced', 'מתקדם')], max_length=20)),
                ('stem_html_he', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('avg_time_seconds', models.PositiveSmallIntegerField(default=60)),
                ('usage_context', models.CharField(choices=[('comprehension', 'בדיקת הבנה'), ('practice', 'תרגול'), ('exam', 'מבחן')], max_length=20)),
                ('senior_insight_he', models.TextField(blank=True)),
                ('last_calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.module')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('topic_tags', models.ManyToManyField(blank=True, to='content.tag')),
            ],
            options={
                'verbose_name': 'שאלה',
                'verbose_name_plural': 'שאלות',
            },
        ),
        migrations.CreateModel(
            name='QuestionExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_html_he', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='content.question')),
            ],
            options={
                'verbose_name': 'הסבר לשאלה',
                'verbose_name_plural': 'הסברים לשאלות',
            },
        ),
        migrations.CreateModel(
            name='ModuleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('component_type', models.CharField(choices=[('reading', 'קריאה'), ('comprehension', 'בדיקת הבנה'), ('exercises', 'תרגילים'), ('summary', 'סיכום')], max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('body_html_he', models.TextField(blank=True)),
                ('instructions_he', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='content.module')),
            ],
            options={
                'verbose_name': 'רכיב מודול',
                'verbose_name_plural': 'רכיבי מודול',
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_he', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('distractor_rationale_he', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
            ],
            options={
                'verbose_name': 'תשובה אפשרית',
                'verbose_name_plural': 'תשובות אפשריות',
                'ordering': ['display_order'],
                'unique_together': {('question', 'display_order')},
            },
        ),
    ]
